training_data = []

training_data.append({"class":"depressed", "sentence":"i am so sad"})
training_data.append({"class":"depressed", "sentence":"i am ending my life today"})
training_data.append({"class":"depressed", "sentence":"i will never be cured"})
training_data.append({"class":"depressed", "sentence":"i am so depressed now"})
training_data.append({"class":"depressed", "sentence":"this is terrible"})
training_data.append({"class":"depressed", "sentence":"want to die"})
training_data.append({"class":"depressed", "sentence":"i feel like killing myself"})
training_data.append({"class":"depressed", "sentence":"i can never be happy in life"})
training_data.append({"class":"depressed", "sentence":"i cant do this anymore"})
training_data.append({"class":"depressed", "sentence":"this is the worst day of my life"})
training_data.append({"class":"depressed", "sentence":"terrible day"})
training_data.append({"class":"depressed", "sentence":"suicide"})
training_data.append({"class":"depressed", "sentence":"death"})
training_data.append({"class":"depressed", "sentence":"im never going to get a bike"})
training_data.append({"class":"depressed", "sentence":"i feel so gloomy today"})
training_data.append({"class":"depressed", "sentence":"i feel so low"})
training_data.append({"class":"depressed", "sentence":"god why does this happen to me"})
training_data.append({"class":"depressed", "sentence":"i feel like shit"})
training_data.append({"class":"depressed", "sentence":"my life sucks"})
training_data.append({"class":"depressed", "sentence":"i hate my life"})
training_data.append({"class":"depressed", "sentence":"i cant believe she did this to me"})
training_data.append({"class":"depressed", "sentence":"i dont think i can recover from this shit"})
training_data.append({"class":"depressed", "sentence":"i will miss her dearly"})
training_data.append({"class":"depressed", "sentence":"i dont think anyone will ever take her place"})
training_data.append({"class":"depressed", "sentence":"i cant take this loss"})
training_data.append({"class":"depressed", "sentence":"ill be dead if this continues"})
training_data.append({"class":"depressed", "sentence":"you're the reason for all this misery"})
training_data.append({"class":"depressed", "sentence":"maybe i dont need to live anymore"})
training_data.append({"class":"depressed", "sentence":"its time i left the world"})
training_data.append({"class":"depressed", "sentence":"im so frustrated"})
training_data.append({"class":"depressed", "sentence":"i cant take this much stress"})
training_data.append({"class":"depressed", "sentence":"i feel so empty"})
training_data.append({"class":"depressed", "sentence":"my life has no meaning"})
training_data.append({"class":"depressed", "sentence":"im clouded with guilt"})
training_data.append({"class":"depressed", "sentence":"I'm lost without love."})
training_data.append({"class":"depressed", "sentence":"I just want to feel like I belong"})
training_data.append({"class":"depressed", "sentence":"My silence is just another word for pain "})
training_data.append({"class":"depressed", "sentence":"Sadness flies away on the wings of time"})
training_data.append({"class":"depressed", "sentence":"Sadness is but a wall between two gardens."})
training_data.append({"class":"depressed", "sentence":"he tragedy of life is not so much what men suffer, but rather what they miss."})
training_data.append({"class":"depressed", "sentence":"The tragedy of life is not that it ends so soon, but that we wait so long to begin it"})
training_data.append({"class":"depressed", "sentence":"I had rather have a fool make me merry, than experience make me sad"})
training_data.append({"class":"depressed", "sentence":"Life isn't fair. It's just fairer than death, that's all."})
training_data.append({"class":"depressed", "sentence":"There is only one rain cloud in the sky...and it's raining on me. Somehow I'm not surprised"})
training_data.append({"class":"depressed", "sentence":"Words hurt more than anything else can, because they last, sometimes forever."})
training_data.append({"class":"depressed", "sentence":"A sad thing in life is that sometimes you meet someone who means a lot to you only to find out in the end that it was never bound to be and you just have to let go"})
training_data.append({"class":"depressed", "sentence":"my life has no meaning"})
training_data.append({"class":"depressed", "sentence":"im clouded with guilt"})
training_data.append({"class":"depressed", "sentence":"Better by far you should forget and smile than that you should remember and be sad."})
training_data.append({"class":"depressed", "sentence":"He is a hard man who is only just, and a sad one who is only wise"})
training_data.append({"class":"depressed", "sentence":"im hurt"})
training_data.append({"class":"depressed", "sentence":"why is this happening to me"})
training_data.append({"class":"depressed", "sentence":"everything bad happens to me"})
training_data.append({"class":"depressed", "sentence":"the world is unfair to me"})
training_data.append({"class":"depressed", "sentence":"im so sad.it will rain on me"})
training_data.append({"class":"depressed", "sentence":"suicide is bliss"})
training_data.append({"class":"depressed", "sentence":"im going to to cry"})
training_data.append({"class":"depressed", "sentence":"i will cry"})
training_data.append({"class":"depressed", "sentence":"i cant stop crying"})
training_data.append({"class":"depressed", "sentence":"i dont want to live life happily"})
training_data.append({"class":"depressed", "sentence":"im a very lonely person"})
training_data.append({"class":"depressed", "sentence":"everyone wants to hurt me"})
training_data.append({"class":"depressed", "sentence":"my life is depressing"})
training_data.append({"class":"depressed", "sentence":"i hate my life"})
training_data.append({"class":"depressed", "sentence":"i hate the face that i have to live"})
training_data.append({"class":"depressed", "sentence":"im depressed"})
training_data.append({"class":"depressed", "sentence":"i want to end my life"})
training_data.append({"class":"depressed", "sentence":"suicide is key"})
training_data.append({"class":"depressed", "sentence":"hurts alot"})
training_data.append({"class":"depressed", "sentence":"hurts to know"})
training_data.append({"class":"depressed", "sentence":"im hurt alot"})
training_data.append({"class":"depressed", "sentence":"i am alone all the time"})
training_data.append({"class":"depressed", "sentence":"i feel lonely"})
training_data.append({"class":"depressed", "sentence":"alone always"})
training_data.append({"class":"depressed", "sentence":"loneliness is my lifetime acheivement"})
training_data.append({"class":"depressed", "sentence":"i dont deserve anything"})
training_data.append({"class":"depressed", "sentence":"i dont deserve this"})
training_data.append({"class":"depressed", "sentence":"i dont deserve anything"})
training_data.append({"class":"depressed", "sentence":"im depressed"})
training_data.append({"class":"depressed", "sentence":"im going into depression"})
training_data.append({"class":"depressed", "sentence":"im failing"})
training_data.append({"class":"depressed", "sentence":"i have failed"})
training_data.append({"class":"depressed", "sentence":"im failing alot"})
training_data.append({"class":"depressed", "sentence":"im a failure"})
training_data.append({"class":"depressed", "sentence":"im disheartened with the results"})
training_data.append({"class":"depressed", "sentence":"i will fail now also"})
training_data.append({"class":"depressed", "sentence":"i failed alone"})
training_data.append({"class":"depressed", "sentence":"alone among people"})
training_data.append({"class":"depressed", "sentence":"im destroyed"})
training_data.append({"class":"depressed", "sentence":"my life is destroyed"})
training_data.append({"class":"depressed", "sentence":"i am dead"})
training_data.append({"class":"depressed", "sentence":"i want to die"})
training_data.append({"class":"depressed", "sentence":"i wanna die"})
training_data.append({"class":"depressed", "sentence":"death is nearing me"})
training_data.append({"class":"depressed", "sentence":"im going to hell"})
training_data.append({"class":"depressed", "sentence":"i hate my life"})
training_data.append({"class":"depressed", "sentence":"i am so unhappy"})
training_data.append({"class":"depressed", "sentence":"i am not happy at all"})
training_data.append({"class":"depressed", "sentence":"i am saaaaaaaaaaaaaaaaad"})
training_data.append({"class":"depressed", "sentence":"I hate myself"})
training_data.append({"class":"depressed", "sentence":"Im not fit to live"})
training_data.append({"class":"depressed", "sentence":"My Friend kicked the bucket Last Night."})
training_data.append({"class":"depressed", "sentence":"I feel like drinking acid"})
training_data.append({"class":"depressed", "sentence":"Its all over! "})
training_data.append({"class":"depressed", "sentence":"I hate everyone who's beside me."})
training_data.append({"class":"depressed", "sentence":"I want to commit suicide"})
training_data.append({"class":"depressed", "sentence":"I hope my last breath is a sigh of relief"})
training_data.append({"class":"depressed", "sentence":"My world is doomed."})
training_data.append({"class":"depressed", "sentence":"my life sucks"})
training_data.append({"class":"depressed", "sentence":"I feel Like leaving everything behind"})
training_data.append({"class":"depressed", "sentence":"Friends are the saddest part of life right now"})
training_data.append({"class":"depressed", "sentence":"I want to eat poison and die"})
training_data.append({"class":"depressed", "sentence":"Somebody kill me"})
training_data.append({"class":"depressed", "sentence":"Get a knife and stab me"})
training_data.append({"class":"depressed", "sentence":"what will happen to my life?"})
training_data.append({"class":"depressed", "sentence":"No body loves me"})
training_data.append({"class":"depressed", "sentence":"I am worthless"})
training_data.append({"class":"depressed", "sentence":"God never helped me"})
training_data.append({"class":"depressed", "sentence":"I have no one to help me"})
training_data.append({"class":"depressed", "sentence":"She suffers from depression, so she hides it behind a fake smile."})
training_data.append({"class":"depressed", "sentence":"My world has come to an end"})
training_data.append({"class":"depressed", "sentence":"I feel like being alone."})
training_data.append({"class":"depressed", "sentence":"I am feeling low"})
training_data.append({"class":"depressed", "sentence":"I have no one for me"})
training_data.append({"class":"depressed", "sentence":"I wish I had more friends"})
training_data.append({"class":"depressed", "sentence":"I wish I was cared by someone"})
training_data.append({"class":"depressed", "sentence":"I want to cry"})
training_data.append({"class":"depressed", "sentence":"I wish to be alone"})
training_data.append({"class":"depressed", "sentence":"I want to leave everything and everyone"})
training_data.append({"class":"depressed", "sentence":"I want to stay alone"})
training_data.append({"class":"depressed", "sentence":"He was depressed because his wife left him."})
training_data.append({"class":"depressed", "sentence":"Im so fucked"})
training_data.append({"class":"depressed", "sentence":"I am lost, all alone"})
training_data.append({"class":"depressed", "sentence":"I want to hit myself"})
training_data.append({"class":"depressed", "sentence":"I am fit for nothing"})
training_data.append({"class":"depressed", "sentence":"I want to shout at myself.."})
training_data.append({"class":"depressed", "sentence":"Nothing much left in life.So I don't want to live"})
training_data.append({"class":"depressed", "sentence":"I am depresssssssed"})
training_data.append({"class":"depressed", "sentence":"Leave me alone"})
training_data.append({"class":"depressed", "sentence":"Nothing can be done now"})
training_data.append({"class":"depressed", "sentence":"Constant feeling of being sad"})
training_data.append({"class":"depressed", "sentence":"I lost my phone."})
training_data.append({"class":"depressed", "sentence":"Nobody loves me."})
training_data.append({"class":"depressed", "sentence":"I cant play"})





training_data.append({"class":"happy", "sentence":"this is the best day ever"})
training_data.append({"class":"happy", "sentence":"yay"})
training_data.append({"class":"happy", "sentence":"this is lit af"})
training_data.append({"class":"happy", "sentence":" this is damn trippy"})
training_data.append({"class":"happy", "sentence":"this is the best shit ever"})
training_data.append({"class":"happy", "sentence":"i am going to party today"})
training_data.append({"class":"happy", "sentence":"i love alcohol, beer and vodka"})
training_data.append({"class":"happy", "sentence":"wow"})
training_data.append({"class":"happy", "sentence":"i like smoking up"})
training_data.append({"class":"happy", "sentence":"i like beer"})
training_data.append({"class":"happy", "sentence":"i love ice-cream"})
training_data.append({"class":"happy", "sentence":"ice-cream is amazing"})
training_data.append({"class":"happy", "sentence":"im so ecstatic"})
training_data.append({"class":"happy", "sentence":"this is the best day of my life"})
training_data.append({"class":"happy", "sentence":"i am so happy"})
training_data.append({"class":"happy", "sentence":"i feel like flying"})
training_data.append({"class":"happy", "sentence":"im the best"})
training_data.append({"class":"happy", "sentence":"im on top of the world"})
training_data.append({"class":"happy", "sentence":"she's the best thing that EVER happened to me"})
training_data.append({"class":"happy", "sentence":"im on cloud nine"})
training_data.append({"class":"happy", "sentence":"im going to have a baby"})
training_data.append({"class":"happy", "sentence":"this is amazing"})
training_data.append({"class":"happy", "sentence":"beautiful weather"})
training_data.append({"class":"happy", "sentence":"omg wow"})
training_data.append({"class":"happy", "sentence":"this is euphoric"})
training_data.append({"class":"happy", "sentence":"i am terribly happy"})
training_data.append({"class":"happy", "sentence":"i am happily married"})
training_data.append({"class":"happy", "sentence":"i love watching porn"})
training_data.append({"class":"happy", "sentence":"this chicken tastes so good"})
training_data.append({"class":"happy", "sentence":"satisfied"})
training_data.append({"class":"happy", "sentence":"i love you"})
training_data.append({"class":"happy", "sentence":"love is a beautiful thing"})
training_data.append({"class":"happy", "sentence":"love at its best"})
training_data.append({"class":"happy", "sentence":"im on cloud 9 today"})
training_data.append({"class":"happy", "sentence":"i am never sad"})
training_data.append({"class":"happy", "sentence":"this is the best day of my life"})
training_data.append({"class":"happy", "sentence":"best day ever"})
training_data.append({"class":"happy", "sentence":"laughing is key"})
training_data.append({"class":"happy", "sentence":"laughd alot today"})
training_data.append({"class":"happy", "sentence":"love has this warmth"})
training_data.append({"class":"happy", "sentence":"this is love"})
training_data.append({"class":"happy", "sentence":"not sad today"})
training_data.append({"class":"happy", "sentence":"not sad"})
training_data.append({"class":"happy", "sentence":"im not disheartened"})
training_data.append({"class":"happy", "sentence":"life at its best"})
training_data.append({"class":"happy", "sentence":"life is beautiful"})
training_data.append({"class":"happy", "sentence":"wow this is amazing"})
training_data.append({"class":"happy", "sentence":"life has never been this good"})
training_data.append({"class":"happy", "sentence":"this is beautiful"})
training_data.append({"class":"happy", "sentence":"yayy!!!!"})
training_data.append({"class":"happy", "sentence":"not sad"})
training_data.append({"class":"happy", "sentence":"not a bad day"})
training_data.append({"class":"happy", "sentence":"not horrible today"})
training_data.append({"class":"happy", "sentence":"not a bad time"})
training_data.append({"class":"happy", "sentence":"not a bad saying"})
training_data.append({"class":"happy", "sentence":"the best time since forever"})
training_data.append({"class":"happy", "sentence":"my team won the match today"})
training_data.append({"class":"happy", "sentence":"i love royal challengers bangalore"})
training_data.append({"class":"happy", "sentence":"im going on a holiday"})
training_data.append({"class":"happy", "sentence":"i love to watch him play"})
training_data.append({"class":"happy", "sentence":"i love playing football"})
training_data.append({"class":"happy", "sentence":"i love it when cops chase me"})
training_data.append({"class":"happy", "sentence":"I love myself"})
training_data.append({"class":"happy", "sentence":"I went dancing with my chick yesterday"})
training_data.append({"class":"happy", "sentence":"I am very excited about the trek."})
training_data.append({"class":"happy", "sentence":"I love going on longdrives"})
training_data.append({"class":"happy", "sentence":"I love clicking pictures"})
training_data.append({"class":"happy", "sentence":"I love shopping"})
training_data.append({"class":"happy", "sentence":"I choose to be happy"})
training_data.append({"class":"happy", "sentence":"Dancing is my passion."})
training_data.append({"class":"happy", "sentence":"I love travelling."})
training_data.append({"class":"happy", "sentence":"I like hanging out with my friends."})
training_data.append({"class":"happy", "sentence":"Everybody loves me."})
training_data.append({"class":"happy", "sentence":"I love to play the guitar"})
training_data.append({"class":"happy", "sentence":"I love maths"})
training_data.append({"class":"happy", "sentence":"I love dancing"})
training_data.append({"class":"happy", "sentence":"I have an amazing family"})
training_data.append({"class":"happy", "sentence":"I have amazing friends"})
training_data.append({"class":"happy", "sentence":"I love panipuri"})
training_data.append({"class":"happy", "sentence":"I love chocolate"})
training_data.append({"class":"happy", "sentence":"Ice-creams are very delicious"})
training_data.append({"class":"happy", "sentence":"Street food is very tasty"})
training_data.append({"class":"happy", "sentence":"I feel Happy when I achieve my daily targets."})
training_data.append({"class":"happy", "sentence":"I love playing ludo"})
training_data.append({"class":"happy", "sentence":"Live for the moments you can't put into words."})
training_data.append({"class":"happy", "sentence":"I helped so many people today"})
training_data.append({"class":"happy", "sentence":"Happiness is when i meet my best friend after a long time."})
training_data.append({"class":"happy", "sentence":"I love playing cricket"})
training_data.append({"class":"happy", "sentence":"I love my cats"})
training_data.append({"class":"happy", "sentence":"I wanna sing and dance"})
training_data.append({"class":"happy", "sentence":"i love pizza"})
training_data.append({"class":"happy", "sentence":"I am haaaaaaapppy"})
training_data.append({"class":"happy", "sentence":"It's such a beautiful day here, isn't it ?"})
training_data.append({"class":"happy", "sentence":"You are the best"})
training_data.append({"class":"happy", "sentence":"Start each day with a grateful heart"})
training_data.append({"class":"happy", "sentence":"I won a lottery."})
training_data.append({"class":"happy", "sentence":"Guess what,tomorrow is holiday!"})
training_data.append({"class":"happy", "sentence":"Today is my birthday!"})
training_data.append({"class":"happy", "sentence":"A surprise gift,hurray!"})

training_data.append({"class":"angry", "sentence":"get lost"})
training_data.append({"class":"angry", "sentence":" wtf"})
training_data.append({"class":"angry", "sentence":"i hate him"})
training_data.append({"class":"angry", "sentence":"hes the most disgusting person ever"})
training_data.append({"class":"angry", "sentence":"motherfucking piece of shit"})
training_data.append({"class":"angry", "sentence":"stop pissing me off"})
training_data.append({"class":"angry", "sentence":" pathetic you are"})
training_data.append({"class":"angry", "sentence":"get lost maniac"})
training_data.append({"class":"angry", "sentence":"you suck"})
training_data.append({"class":"angry", "sentence":"i am so angry at you"})
training_data.append({"class":"angry", "sentence":"dont bother me"})
training_data.append({"class":"angry", "sentence":"go away piece of shit"})
training_data.append({"class":"angry", "sentence":"leave me alone"})
training_data.append({"class":"angry", "sentence":"go away forever"})
training_data.append({"class":"angry", "sentence":"you are the worst"})
training_data.append({"class":"angry", "sentence":"worst time ever"})
training_data.append({"class":"angry", "sentence":" this is not good at all"})
training_data.append({"class":"angry", "sentence":"dont you dare"})
training_data.append({"class":"angry", "sentence":"i dare you"})
training_data.append({"class":"angry", "sentence":"too much attitude"})
training_data.append({"class":"angry", "sentence":"annoying as hell"})
training_data.append({"class":"angry", "sentence":"to hell with you"})
training_data.append({"class":"angry", "sentence":"get away"})
training_data.append({"class":"angry", "sentence":"lavanya talks too much"})
training_data.append({"class":"angry", "sentence":"thunne unnu"})
training_data.append({"class":"angry", "sentence":"saale madarchod"})
training_data.append({"class":"angry", "sentence":"teri maa ki saaki naaka"})
training_data.append({"class":"angry", "sentence":"see, i dont give a fuck"})
training_data.append({"class":"angry", "sentence":"stop acting like a dickhead"})
training_data.append({"class":"angry", "sentence":"fml"})
training_data.append({"class":"angry", "sentence":"can you please stop acting like an asshole"})
training_data.append({"class":"angry", "sentence":"stop harrassing me"})
training_data.append({"class":"angry", "sentence":"stop eating my lunch all the time"})
training_data.append({"class":"angry", "sentence":"stop fucking that bitch, come lay with me"})
training_data.append({"class":"angry", "sentence":"she's not listening to me"})
training_data.append({"class":"angry", "sentence":"he drives like a piece of shit"})
training_data.append({"class":"angry", "sentence":"imma kill you"})
training_data.append({"class":"angry", "sentence":"you stupid ass hoe"})
training_data.append({"class":"angry", "sentence":"im going to cut your dick off"})
training_data.append({"class":"angry", "sentence":"imma rip your balls out"})
training_data.append({"class":"angry", "sentence":"vengeance will be served"})
training_data.append({"class":"angry", "sentence":"i will have my revenge"})
training_data.append({"class":"angry", "sentence":"fuck my life"})
training_data.append({"class":"angry", "sentence":"im not a bitch like you "})
training_data.append({"class":"angry", "sentence":"fuck off bitch don't piss me off"})
training_data.append({"class":"angry", "sentence":"I want to kill my friend"})
training_data.append({"class":"angry", "sentence":"I hate people with imperious tone."})
training_data.append({"class":"angry", "sentence":"I hate back stabbing people."})
training_data.append({"class":"angry", "sentence":"I don't like liars."})
training_data.append({"class":"angry", "sentence":"I like violence."})
training_data.append({"class":"angry", "sentence":"Dont show your face to me"})
training_data.append({"class":"angry", "sentence":"Get out of my room"})
training_data.append({"class":"angry", "sentence":"Go to hell"})
training_data.append({"class":"angry", "sentence":"Fuck off"})
training_data.append({"class":"angry", "sentence":"Fuck you"})
training_data.append({"class":"angry", "sentence":"Shame on your part"})
training_data.append({"class":"angry", "sentence":"I feel like slapping you"})
training_data.append({"class":"angry", "sentence":"Just get the hell out of my life"})
training_data.append({"class":"angry", "sentence":"My boyfriend betrayed me."})
training_data.append({"class":"angry", "sentence":"I will have my revenge"})
training_data.append({"class":"angry", "sentence":"vengeance is served"})
training_data.append({"class":"angry", "sentence":"don't touch my guitar and without my permission."})
training_data.append({"class":"angry", "sentence":"I hate when people don't listen to me."})
training_data.append({"class":"angry", "sentence":"I don't like narrow minded people"})
training_data.append({"class":"angry", "sentence":"Everyone just get the hell out of here"})
training_data.append({"class":"angry", "sentence":"Enough is enough"})
training_data.append({"class":"angry", "sentence":"Just get lost"})
training_data.append({"class":"angry", "sentence":"You are a very irresponsible person."})
training_data.append({"class":"angry", "sentence":"stop talking to me"})
training_data.append({"class":"angry", "sentence":"Go to hell"})
training_data.append({"class":"angry", "sentence":"I am aaaaaaaaaangry"})
training_data.append({"class":"angry", "sentence":"Get the hell out of my sight !!!"})
training_data.append({"class":"angry", "sentence":"I want to kick him in balls"})
training_data.append({"class":"angry", "sentence":"I am really mad at you."})
training_data.append({"class":"angry", "sentence":"She ruined my project"})
training_data.append({"class":"angry", "sentence":"she slapped me"})
training_data.append({"class":"angry", "sentence":"they insulted me"})




training_data.append({"class":"scared", "sentence":"please dont do this to me"})
training_data.append({"class":"scared", "sentence":"im really scared now"})
training_data.append({"class":"scared", "sentence":"this is frightening"})
training_data.append({"class":"scared", "sentence":"im haunted"})
training_data.append({"class":"scared", "sentence":"this is such a nightmare"})
training_data.append({"class":"scared", "sentence":"im too scared to do this"})
training_data.append({"class":"scared", "sentence":"he's bullying me and i can't take it anymore"})
training_data.append({"class":"scared", "sentence":"im getting bullied at school"})
training_data.append({"class":"scared", "sentence":"i live in constant fear of him"})
training_data.append({"class":"scared", "sentence":"i cant get out of the house because he may kill me"})
training_data.append({"class":"scared", "sentence":"i think hes gonna kill me"})
training_data.append({"class":"scared", "sentence":"im scared that she may do something"})
training_data.append({"class":"scared", "sentence":"i dont want him to kill himself"})
training_data.append({"class":"scared", "sentence":"im scared of the dark"})
training_data.append({"class":"scared", "sentence":"im scared that the dog will bite me"})
training_data.append({"class":"scared", "sentence":"im scared ill die a virgin"})
training_data.append({"class":"scared", "sentence":"im scared ill get rejected"})
training_data.append({"class":"scared", "sentence":"i fear death"})
training_data.append({"class":"scared", "sentence":"okay this is not funny"})
training_data.append({"class":"scared", "sentence":"i hope i dont get murdered"})
training_data.append({"class":"scared", "sentence":"i hope that lady doesnt kill me"})
training_data.append({"class":"scared", "sentence":"im scared ill die crossing the road"})
training_data.append({"class":"scared", "sentence":"im scared of going fast"})
training_data.append({"class":"scared", "sentence":"im scared ill give in to temptation and do drugs"})
training_data.append({"class":"scared", "sentence":"im really scared of him"})
training_data.append({"class":"scared", "sentence":"There's Something Behind The Door."})
training_data.append({"class":"scared", "sentence":"I'm having nightmares."})
training_data.append({"class":"scared", "sentence":"Omg! I just watched a horror movie, I am unable to sleep tonight."})
training_data.append({"class":"scared", "sentence":"I'm afraid of ghosts and darkness"})
training_data.append({"class":"scared", "sentence":"I am worried that I would be fired from the job."})
training_data.append({"class":"scared", "sentence":"I am scared of being robbed."})
training_data.append({"class":"scared", "sentence":"I am scared of ghosts."})
training_data.append({"class":"scared", "sentence":"I am sacred that I will not Score well in my exams"})
training_data.append({"class":"scared", "sentence":"Oh I am worried"})
training_data.append({"class":"scared", "sentence":"I am worried about my result"})
training_data.append({"class":"scared", "sentence":"This time I will fail and I am worried about this"})
training_data.append({"class":"scared", "sentence":"My dad might slap me"})
training_data.append({"class":"scared", "sentence":"I'm scared to go into the scary house"})
training_data.append({"class":"scared", "sentence":"Scary house scares me"})
training_data.append({"class":"scared", "sentence":"Oh God I am scared to sit in this ride"})
training_data.append({"class":"scared", "sentence":"I'm scared because I may fall"})
training_data.append({"class":"scared", "sentence":"I'm scared of animals"})
training_data.append({"class":"scared", "sentence":"I am scared of snakes"})
training_data.append({"class":"scared", "sentence":"I was kind of scared they might shoot us"})
training_data.append({"class":"scared", "sentence":"Horror movies are scary."})
training_data.append({"class":"scared", "sentence":"Everyone was scared when the teacher entered the class room."})
training_data.append({"class":"scared", "sentence":"I am scared when I am alone at home."})
training_data.append({"class":"scared", "sentence":"I am afraid to travel alone"})
training_data.append({"class":"scared", "sentence":"I am scared of heights"})
training_data.append({"class":"scared", "sentence":"Scared of cockroaches"})
training_data.append({"class":"scared", "sentence":"It looks like it's haunted."})
training_data.append({"class":"scared", "sentence":"I don't feel safe here AT ALL!"})
training_data.append({"class":"scared", "sentence":"I might be fined for driving without licence."})
training_data.append({"class":"scared", "sentence":"Exam results"})
training_data.append({"class":"scared", "sentence":"The road through the 18th avenue leading to the dead widows house is scary"})




training_data.append({"class":"sad", "sentence":"my team lost the finals"})
training_data.append({"class":"sad", "sentence":"i am so unhappy"})
training_data.append({"class":"sad", "sentence":"prajwal has to sit next to lavanya everyday"})
training_data.append({"class":"sad", "sentence":"the results were diheartening"})
training_data.append({"class":"sad", "sentence":"i think i should stop dancing"})
training_data.append({"class":"sad", "sentence":"i wont be able to come to play today :("})
training_data.append({"class":"sad", "sentence":"i cant go for a holiday"})
training_data.append({"class":"sad", "sentence":"my car broke down"})
training_data.append({"class":"sad", "sentence":"i cant walk properly"})
training_data.append({"class":"sad", "sentence":"i may not be able to see for the rest of my life"})
training_data.append({"class":"sad", "sentence":"i haven't seen my friend in ages"})
training_data.append({"class":"sad", "sentence":"shes annoyed with me"})
training_data.append({"class":"sad", "sentence":"my pizza fell down on the floor"})
training_data.append({"class":"sad", "sentence":"the dog ate my car keys"})
training_data.append({"class":"sad", "sentence":"i lost the match"})
training_data.append({"class":"sad", "sentence":"i cant attend the concert"})
training_data.append({"class":"sad", "sentence":"i cant play anymore"})
training_data.append({"class":"sad", "sentence":"my team sucks"})
training_data.append({"class":"sad", "sentence":"i feel sad"})
training_data.append({"class":"sad", "sentence":"im so sad"})
training_data.append({"class":"sad", "sentence":"she should've won"})
training_data.append({"class":"sad", "sentence":"i shouldve done better in my exams"})
training_data.append({"class":"sad", "sentence":"my holidays are getting over"})
training_data.append({"class":"sad", "sentence":"i havent watched a movie in ages"})
training_data.append({"class":"sad", "sentence":"i havent eaten pizza this week"})
training_data.append({"class":"sad", "sentence":"i have to sacrifice for the greater good"})
training_data.append({"class":"sad", "sentence":"im gonna have to stop playing clash royale"})
training_data.append({"class":"sad", "sentence":"Oh no! The trek got cancelled :("})
training_data.append({"class":"sad", "sentence":"Don't ignore me. "})
training_data.append({"class":"sad", "sentence":"Friendship hurts"})
training_data.append({"class":"sad", "sentence":"My buddy passed away."})
training_data.append({"class":"sad", "sentence":"My friend cheated me"})
training_data.append({"class":"sad", "sentence":"My boyfriend ditched me"})
training_data.append({"class":"sad", "sentence":"Oh my uncle expired"})
training_data.append({"class":"sad", "sentence":"My result was undoubtedly a bad one"})
training_data.append({"class":"sad", "sentence":"My best friend isn't feeling well"})
training_data.append({"class":"sad", "sentence":"i met with an accident"})
training_data.append({"class":"sad", "sentence":"My father hit me"})
training_data.append({"class":"sad", "sentence":"How sad it would be if she didn't care about the one thing that defined him."})
training_data.append({"class":"sad", "sentence":"I lost my job."})
training_data.append({"class":"sad", "sentence":"Everything is going worng!"})
training_data.append({"class":"sad", "sentence":"I am not intrested in any work"})
training_data.append({"class":"sad", "sentence":"I just want to leave everything and go away"})
training_data.append({"class":"sad", "sentence":"I feel sad when my mom doesnt talk to me."})
training_data.append({"class":"sad", "sentence":"we dont get holidays."})
training_data.append({"class":"sad", "sentence":"my fate is too bad"})
training_data.append({"class":"sad", "sentence":"my friends hate me"})
training_data.append({"class":"sad", "sentence":"I am saaaaaaaaaad"})
training_data.append({"class":"sad", "sentence":"Not in the mood to talk"})
training_data.append({"class":"sad", "sentence":"I can't pay my bills"})
training_data.append({"class":"sad", "sentence":"Going back to hostel"})
training_data.append({"class":"sad", "sentence":"I couldn't help her"})







training_data.append({"class":"neutral", "sentence":"i am not unhappy"})
training_data.append({"class":"neutral", "sentence":"i am not disheartened"})
training_data.append({"class":"neutral", "sentence":"i am not irresponsible"})
training_data.append({"class":"neutral", "sentence":"i cant not care"})
training_data.append({"class":"neutral", "sentence":"i dont support anyone or anything"})
training_data.append({"class":"neutral", "sentence":"the heat is not unbearable"})
training_data.append({"class":"neutral", "sentence":"this song is decent"})
training_data.append({"class":"neutral", "sentence":"this is a neutral sentence"})
training_data.append({"class":"neutral", "sentence":"the beach is filled with sand"})
training_data.append({"class":"neutral", "sentence":"she looks like my mom"})
training_data.append({"class":"neutral", "sentence":"the beach is really blue today"})
training_data.append({"class":"neutral", "sentence":"he's talking to someone"})
training_data.append({"class":"neutral", "sentence":"im doing an internship for the summer"})
training_data.append({"class":"neutral", "sentence":"i have too many clothes"})
training_data.append({"class":"neutral", "sentence":"its sunny today"})
training_data.append({"class":"neutral", "sentence":"the sun rises in the east"})
training_data.append({"class":"neutral", "sentence":"i have curly hair"})
training_data.append({"class":"neutral", "sentence":"the banks are closed today"})
training_data.append({"class":"neutral", "sentence":"i have a black bag"})
training_data.append({"class":"neutral", "sentence":"there is a cricket match in my city today"})
training_data.append({"class":"neutral", "sentence":"they sit next to each other"})
training_data.append({"class":"neutral", "sentence":"my keyboard has a white backlight"})
training_data.append({"class":"sad", "sentence":"fuck you dog"})
training_data.append({"class":"sad", "sentence":"i still love her"})
training_data.append({"class":"sad", "sentence":"i wanna kill myself with a knife"})
training_data.append({"class":"angry", "sentence":"i will kill my dog"})

training_data.append({"class":"disgusted", "sentence":"yuck this is disgusting"})
training_data.append({"class":"disgusted", "sentence":"ewww!"})
training_data.append({"class":"disgusted", "sentence":"im cringing"})
training_data.append({"class":"disgusted", "sentence":"can you get any worse?"})
training_data.append({"class":"disgusted", "sentence":"this tv show is gross"})
training_data.append({"class":"disgusted", "sentence":"i can't wach this shit anymore"})
training_data.append({"class":"disgusted", "sentence":"you disgust me"})
training_data.append({"class":"disgusted", "sentence":"human centipede"})
training_data.append({"class":"disgusted", "sentence":"this movie is terrible"})
training_data.append({"class":"disgusted", "sentence":"gross"})
training_data.append({"class":"disgusted", "sentence":"Ugh"})
training_data.append({"class":"disgusted", "sentence":"urghh"})
training_data.append({"class":"disgusted", "sentence":"he expressed a severe distaste towards pork"})
training_data.append({"class":"disgusted", "sentence":"i loathe her"})
training_data.append({"class":"disgusted", "sentence":"abhorrence"})
training_data.append({"class":"disgusted", "sentence":"they were revolting"})
training_data.append({"class":"disgusted", "sentence":"these people hate each other"})
training_data.append({"class":"disgusted", "sentence":"repungance"})
training_data.append({"class":"disgusted", "sentence":"antipathy"})
training_data.append({"class":"disgusted", "sentence":"gak"})
training_data.append({"class":"disgusted", "sentence":"Ick"})
training_data.append({"class":"disgusted", "sentence":""})
training_data.append({"class":"disgusted", "sentence":""})
training_data.append({"class":"disgusted", "sentence":""})



training_data.append({"class":"surprised", "sentence":"Oh my god!"})
training_data.append({"class":"surprised", "sentence":"I can't believe she did this"})
training_data.append({"class":"surprised", "sentence":"i'll be damned"})
training_data.append({"class":"surprised", "sentence":"it's a wonder"})
training_data.append({"class":"surprised", "sentence":"im gobsmacked"})
training_data.append({"class":"surprised", "sentence":"i nearly fell off my chair"})
training_data.append({"class":"surprised", "sentence":"i leapt out of my skin"})
training_data.append({"class":"surprised", "sentence":"i did not know what hit me"})
training_data.append({"class":"surprised", "sentence":"she was a staggering beauty"})
training_data.append({"class":"surprised", "sentence":"thunderstruck"})
training_data.append({"class":"surprised", "sentence":"i was stupefied"})
training_data.append({"class":"surprised", "sentence":"I could't believe my luck"})
training_data.append({"class":"surprised", "sentence":"i was startled"})
training_data.append({"class":"surprised", "sentence":"my eyes popped out of my head"})
training_data.append({"class":"surprised", "sentence":"i was dumbstruck"})
training_data.append({"class":"surprised", "sentence":"i almost had a heart-attack"})
training_data.append({"class":"surprised", "sentence":"whoa thats awesome!"})
training_data.append({"class":"surprised", "sentence":"I still cant figure out how he did so well"})
training_data.append({"class":"surprised", "sentence":"you gotta be kidding me"})
training_data.append({"class":"surprised", "sentence":"you gotta be shitting me"})
training_data.append({"class":"surprised", "sentence":"this is fucking unbelievable"})
training_data.append({"class":"surprised", "sentence":"gosh!"})
training_data.append({"class":"surprised", "sentence":"bless my soul!"})
training_data.append({"class":"surprised", "sentence":"for the love of god"})
training_data.append({"class":"surprised", "sentence":"crikey!"})
training_data.append({"class":"surprised", "sentence":"i was caught unawares"})
training_data.append({"class":"surprised", "sentence":"i was taken aback by his response"})
training_data.append({"class":"surprised", "sentence":"i really don't know what to say"})







